# PyTorch Lesson: Tensors

Once PyTorch is installed with `pip install torch`, you can import torch as follows:

In [ ]:
import torch
import math

/Users/curtwheeler/VisualStudioCode/Learning/Python/PyTorch/.venv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:295: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


---

## Creating Tensors

---

In PyTorch, one of the simplest ways to create a basic tensor is to use `torch.empty(x, y)`. This function creates a tensor with dimensions `x` by `y`, where each position in the tensor can hold a value. A tensor is essentially a multi-dimensional array, similar to a matrix in math, that can store a list of values across rows and columns. 

### Understanding `torch.empty(x, y)`

When you call `torch.empty(x, y)`, PyTorch allocates memory for a tensor of size `(x, y)`—that is, a tensor with `x` rows and `y` columns. However, this memory space is **not initialized with any values**. Unlike functions like `torch.zeros(x, y)`, which would fill each element with zero, `torch.empty(x, y)` skips the initialization step, leaving the elements filled with whatever was previously in that section of memory.

Mathematically, if you imagine a tensor created with `torch.zeros(2, 3)`, it might look like this:


\begin{bmatrix} 0 & 0 & 0 \\ 0 & 0 & 0 \end{bmatrix}


In contrast, a tensor created with `torch.empty(2, 3)` might look like this:


\begin{bmatrix} 3.4 \times 10^{38} & 0.0000 & -1.2 \times 10^{37} \\ 1.6 \times 10^{27} & -4.9 & 7.3 \end{bmatrix}


These random, “garbage” values are arbitrary data from memory that PyTorch has not overwritten.

#### Why Use `torch.empty`?

Since no values are assigned when using `torch.empty(x, y)`, it can be faster than initializing with zeros or other specific values. This approach is helpful when you plan to immediately overwrite the values in the tensor, as no unnecessary work is done in setting initial values that will be discarded.

### Data Types of Tensors

By default, PyTorch tensors use 32-bit floating-point numbers, which are standard for many machine learning tasks. This means each number in the tensor occupies 32 bits (4 bytes) in memory, following the IEEE 754 standard. In this standard:
- 1 bit is reserved for the **sign** (0 for positive, 1 for negative).
- 8 bits are for the **exponent**, which determines the range.
- 23 bits are for the **mantissa (or significand)**, which represents the precision of the number.

With this structure, a 32-bit floating-point number can represent very small and very large values efficiently but has limitations in terms of precision.

### Other Data Types Supported by PyTorch

PyTorch supports a variety of data types for different needs, as outlined below:

| Category         | Data Type       | Description                        | Alias (if any)  |
|------------------|-----------------|------------------------------------|-----------------|
| Floating-point   | `torch.float32` | 32-bit floating-point              | `torch.float`   |
|                  | `torch.float64` | 64-bit floating-point (higher precision) | `torch.double` |
|                  | `torch.float16` | 16-bit floating-point (lower precision, faster) | `torch.half`   |
|                  | `torch.bfloat16`| 16-bit brain floating-point (special format) |               |
| Integer          | `torch.int8`    | 8-bit signed integer               |                 |
|                  | `torch.int16`   | 16-bit signed integer              | `torch.short`   |
|                  | `torch.int32`   | 32-bit signed integer              | `torch.int`     |
|                  | `torch.int64`   | 64-bit signed integer              | `torch.long`    |
|                  | `torch.uint8`   | 8-bit unsigned integer             |                 |
| Complex          | `torch.complex32` | 32-bit complex number           |                 |
|                  | `torch.complex64` | 64-bit complex number           |                 |
|                  | `torch.complex128`| 128-bit complex number          |                 |
| Boolean          | `torch.bool`    | Boolean (True/False)               |                 |
| Quantized        | `torch.qint8`   | Quantized 8-bit signed integer     |                 |
|                  | `torch.quint8`  | Quantized 8-bit unsigned integer   |                 |
|                  | `torch.qint32`  | Quantized 32-bit signed integer    |                 |
|                  | `torch.quint4x2`| Quantized 4-bit unsigned integer (packed) |     |
| Special          | `torch.float8_e5m2` | 8-bit floating-point (experimental) |      |
|                  | `torch.float8_e4m3fn`| 8-bit floating-point (experimental) |     |

Each of these data types can be chosen based on the balance you want between memory usage and precision. For instance, floating-point numbers (`torch.float32`) are common for neural networks, as they provide good precision with reasonable memory usage. Integer types are often used for indexing or counting, while lower-precision types (e.g., `torch.float16`) may be used to save memory in applications where precision is less critical.

In [ ]:
torch.empty(5,10)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Whereas `torch.zeros(x, y)` initializes a tensor of dimensions `(x, y)` with `0.` (`0.0`) 16-bit floating point values. 

In [5]:
torch.zeros(5,10)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

Certainly! Here’s a description of `torch.ones` and `torch.rand` using mathematical notation.

---

### 1. `torch.ones(x, y)`

The function `torch.ones(x, y)` creates a tensor of shape $(x, y)$ in which **every element is initialized to 1**. This can be expressed as:

$$
\mathbf{T} = \begin{bmatrix} 1 & 1 & \cdots & 1 \\ 1 & 1 & \cdots & 1 \\ \vdots & \vdots & \ddots & \vdots \\ 1 & 1 & \cdots & 1 \end{bmatrix}
$$

where $\mathbf{T}$ is an $x \times y$ matrix in which every entry $T_{ij} = 1$ for all $i \in \{1, \dots, x\}$ and $j \in \{1, \dots, y\}$.

---

### 2. `torch.rand(x, y)`

The function `torch.rand(x, y)` generates a tensor of shape $(x, y)$ where each element is a **random value drawn from a uniform distribution** over the interval $[0, 1)$. This can be mathematically represented as:

$$
\mathbf{R} = \begin{bmatrix} r_{11} & r_{12} & \cdots & r_{1y} \\ r_{21} & r_{22} & \cdots & r_{2y} \\ \vdots & \vdots & \ddots & \vdots \\ r_{x1} & r_{x2} & \cdots & r_{xy} \end{bmatrix}
$$

The element $r_{ij}$ is sampled such that $r_{ij} \in [0, 1)$.

---

### Setting the Random Seed with `torch.manual_seed`

To ensure the matrix $\mathbf{R}$ remains consistent across different runs (i.e., the same values $ r_{ij} $ are generated each time), `torch.manual_seed(seed)` is used. Setting a random seed makes the sequence of random values reproducible, which is useful for consistent debugging and result verification in machine learning experiments. 

--- 

This mathematical format provides a structured way to visualize the outputs from `torch.ones` and `torch.rand` without needing specific example values.

In [6]:
torch.ones(5,10)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [50]:
torch.manual_seed(1234)
torch.rand(5,10)

tensor([[0.0290, 0.4019, 0.2598, 0.3666, 0.0583, 0.7006, 0.0518, 0.4681, 0.6738,
         0.3315],
        [0.7837, 0.5631, 0.7749, 0.8208, 0.2793, 0.6817, 0.2837, 0.6567, 0.2388,
         0.7313],
        [0.6012, 0.3043, 0.2548, 0.6294, 0.9665, 0.7399, 0.4517, 0.4757, 0.7842,
         0.1525],
        [0.6662, 0.3343, 0.7893, 0.3216, 0.5247, 0.6688, 0.8436, 0.4265, 0.9561,
         0.0770],
        [0.4108, 0.0014, 0.5414, 0.6419, 0.2976, 0.7077, 0.4189, 0.0655, 0.8839,
         0.8083]])

### What is the Difference Between a Tensor and a Vector?

In mathematics and machine learning, **tensors** and **vectors** are both important tools for representing data, but they differ in structure, dimensionality, and how they are used.

#### 1. Definition of a Vector

A **vector** is a specific type of tensor—one that is restricted to a single dimension. You can think of a vector as a list of numbers arranged in a straight line. Mathematically, vectors represent quantities with both magnitude and direction, and are commonly used in physics, geometry, and machine learning to describe entities like velocity, force, and weight.

In PyTorch, a vector might look like this:


\text{vector} = \begin{bmatrix} 1.5, 2.3, -0.7, 4.0 \end{bmatrix}


This is a **1-dimensional tensor** with 4 elements. We can represent a vector by using a tensor with shape `(4,)`, which has just one dimension of length 4.

#### 2. Definition of a Tensor

A **tensor** is a more general concept that can represent data in multiple dimensions. Tensors can be thought of as multi-dimensional arrays:
- A **0-dimensional tensor** is a single scalar value, like `5.0`.
- A **1-dimensional tensor** is a vector, as we discussed above.
- A **2-dimensional tensor** is similar to a matrix, with rows and columns, like a spreadsheet or grid of numbers.
- Higher-dimensional tensors (3D, 4D, etc.) can be used to represent even more complex structures. For example, a 3D tensor might represent a stack of matrices (like an RGB image), and a 4D tensor might represent a batch of images with color channels.

In PyTorch, a 2-dimensional tensor (matrix) might look like this:


\text{tensor} = \begin{bmatrix} 1.0 & -2.1 \\ 0.3 & 4.5 \end{bmatrix}


This is a **2-dimensional tensor** with shape `(2, 2)`, having 2 rows and 2 columns.

#### 3. Comparing Tensors and Vectors

| Aspect                  | Vector                                      | Tensor                                         |
|-------------------------|---------------------------------------------|------------------------------------------------|
| **Dimensions**          | 1-dimensional only                          | Can have any number of dimensions (1D, 2D, 3D, etc.) |
| **Shape Example**       | `(4,)`                                      | `(2, 2)` for a 2D tensor, `(3, 3, 3)` for a 3D tensor |
| **Use Cases**           | Representing simple lists of values         | Representing more complex, multi-dimensional data |
| **Example in PyTorch**  | `torch.tensor([1.5, 2.3, -0.7, 4.0])`       | `torch.tensor([[1.0, -2.1], [0.3, 4.5]])`            |

In short:
- **Vectors are one-dimensional tensors** used to represent lists or sequences of values.
- **Tensors are generalized to multiple dimensions**, making them suitable for complex data structures. 

#### 4. When to Use Each

- **Vectors** are ideal for representing simple data, such as features of a single data point (e.g., a list of measurements).
- **Tensors** are essential for handling complex data, such as images, videos, or batches of multiple data points in machine learning, where multi-dimensional representations are crucial.

In machine learning frameworks like PyTorch, vectors and tensors are essentially both handled as tensors, with vectors just being special cases with a single dimension. Understanding this distinction can help you choose the right structure and shape for your data.